[workspace]
members = [
	"fluxer_admin",
	"fluxer_app_proxy",
	"fluxer_common",
	"fluxer_media_proxy",
	"fluxer_gifs",
	"fluxer_svc",
	"fluxer_messages",
	"fluxer_snowflakes",
	"tools/ci",
	"tools/content/update-frozen-snapshot",
	"tools/dev",
	"tools/i18n_auto",
	"fluxer_users",
	"fluxer_unfurl",
	"packages/markdown_parser/rust",
]
exclude = [
	"fluxer_marketing",
	"packages/markdown_parser/rust/fuzz",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
