// SPDX-License-Identifier: AGPL-3.0-or-later

export {
	decodeVoiceEngineV2CodecGossip,
	encodeVoiceEngineV2CodecGossip,
	VOICE_ENGINE_V2_CODEC_GOSSIP_TOPIC,
} from './codecGossip';
export type {VoiceEngineV2Command, VoiceEngineV2CommandType} from './commands';
export {getVoiceEngineV2CommandResourceKey, getVoiceEngineV2CommandTypeResourceKey} from './commands';
export type {
	VoiceEngineV2Event,
	VoiceEngineV2SourceLifecycleTransitionedEvent,
	VoiceEngineV2SourceLifecycleTransitionKind,
} from './events';
export type {
	VoiceEngineV2AudioControls,
	VoiceEngineV2AudioControlsPatch,
	VoiceEngineV2AudioDeviceRole,
	VoiceEngineV2AudioInputDevice,
	VoiceEngineV2AudioMode,
	VoiceEngineV2AudioOutputDevice,
	VoiceEngineV2CameraDevice,
	VoiceEngineV2CameraEncodingOptions,
	VoiceEngineV2CameraOptions,
	VoiceEngineV2Capabilities,
	VoiceEngineV2CodecGossipMessage,
	VoiceEngineV2CodecNegotiationState,
	VoiceEngineV2CodecStreamNegotiation,
	VoiceEngineV2ConnectionModel,
	VoiceEngineV2ConnectionQuality,
	VoiceEngineV2ConnectionStatus,
	VoiceEngineV2ConnectOptions,
	VoiceEngineV2DataOptions,
	VoiceEngineV2DeviceChangeReason,
	VoiceEngineV2DeviceInventory,
	VoiceEngineV2DiagnosticEntry,
	VoiceEngineV2DiagnosticLevel,
	VoiceEngineV2DisconnectReason,
	VoiceEngineV2E2eeState,
	VoiceEngineV2E2eeStatus,
	VoiceEngineV2Error,
	VoiceEngineV2GatewayDesiredVoiceState,
	VoiceEngineV2GatewayVoiceServer,
	VoiceEngineV2GatewayVoiceState,
	VoiceEngineV2GatewayVoiceStateWrite,
	VoiceEngineV2HardwareEncoderCapabilities,
	VoiceEngineV2ImplementationKind,
	VoiceEngineV2InboundStats,
	VoiceEngineV2InboundVideoFrame,
	VoiceEngineV2InboundVideoFrameStats,
	VoiceEngineV2InboundVideoTrack,
	VoiceEngineV2InboundVideoTrackSubscription,
	VoiceEngineV2LatencyDataPoint,
	VoiceEngineV2LifecycleReason,
	VoiceEngineV2LiveKitConnectionState,
	VoiceEngineV2LiveKitRoomState,
	VoiceEngineV2LocalStreamSource,
	VoiceEngineV2MediaModel,
	VoiceEngineV2MediaStatus,
	VoiceEngineV2MicrophoneOptions,
	VoiceEngineV2Model,
	VoiceEngineV2NativeAudioTapOptions,
	VoiceEngineV2NativeCaptureFrame,
	VoiceEngineV2NativeCaptureKind,
	VoiceEngineV2NativeCaptureOptions,
	VoiceEngineV2NativeCaptureSource,
	VoiceEngineV2NativeFrameSinkOptions,
	VoiceEngineV2OperationId,
	VoiceEngineV2OutboundStats,
	VoiceEngineV2OutputDeviceOptions,
	VoiceEngineV2Participant,
	VoiceEngineV2ParticipantVolumeOptions,
	VoiceEngineV2PcmFrame,
	VoiceEngineV2PermissionName,
	VoiceEngineV2PermissionResult,
	VoiceEngineV2PermissionStatus,
	VoiceEngineV2PerTrackStats,
	VoiceEngineV2RemoteTrackQuality,
	VoiceEngineV2RemoteTrackSubscriptionOptions,
	VoiceEngineV2ResourceKey,
	VoiceEngineV2ScreenAudioOptions,
	VoiceEngineV2ScreenEncodingOptions,
	VoiceEngineV2ScreenOptions,
	VoiceEngineV2ScreenPacing,
	VoiceEngineV2SendStats,
	VoiceEngineV2Stats,
	VoiceEngineV2StatsSample,
	VoiceEngineV2StreamNegotiationProjection,
	VoiceEngineV2TimerOptions,
	VoiceEngineV2Track,
	VoiceEngineV2TrackKind,
	VoiceEngineV2TrackSource,
	VoiceEngineV2TransportInfo,
	VoiceEngineV2VideoAccelerationStatus,
	VoiceEngineV2VideoCodec,
	VoiceEngineV2VoiceStats,
	VoiceEngineV2WatchedStream,
	VoiceEngineV2WatchedStreamKey,
} from './types';
